# Generated by Django 4.0.5 on 2022-07-08 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_product_seller_account_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
    ]
