# Generated by Django 4.0.5 on 2022-07-09 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_account_products_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user_photo',
        ),
    ]
